version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: pfm_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=personal_finance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pfm-external-network

  backend:
    image: personal-finance-manager-backend:latest
    container_name: pfm_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/personal_finance
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - pfm-external-network

  currency-converter:
    image: personal-finance-manager-currency-converter:latest
    container_name: pfm_currency_converter
    ports:
      - "8083:8080"
    networks:
      - pfm-external-network

  statistics-service:
    image: personal-finance-manager-statistics-service:latest
    container_name: pfm_statistics_service
    ports:
      - "8084:8080"
    networks:
      - pfm-external-network

  nginx:
    build: ./nginx
    image: personal-finance-manager-nginx:latest
    ports:
      - "80:80"
    networks:
      - pfm-external-network
    depends_on:
      - backend
      - currency-converter
      - statistics-service

volumes:
  postgres_data:

networks:
  pfm-external-network:
    external: true
